### ISSUE TITLE
Add pets API

### ISSUE THREAD

**Issue by Bjornskjald** [Scr1ptK1tt13s/overdeer-api#4]
I tried to add a pet with POST API (as seen in https://docs.scriptkitties.space) but it doesn't work, all I get is `405 Not Allowed`.

![image](https://user-images.githubusercontent.com/26630168/50798151-9646c600-12d7-11e9-9d00-5801abc47c75.png)

**Comment by MilyMilo** [comment]
Ok, so @Scr1ptK1tt13s/doc-team is finally here.
//cc @Naniewicz1337

**Comment by Bjornskjald** [comment]
Will the new API allow for adding pets?

**Comment by MilyMilo** [comment]
no.
